Add option for orthographic projections to sim depth cameras
ascentai/gl_depth_sim pull request #4
Opened 2022-05-18 11:52 UTC by thomascent

## Summary

When checking whether two objects overlap it's useful to be able to render their depth map using an orthographic projection. This PR adds that functionality to `gl_depth_sim`!

To do that, I just added an enum for whether the camera was a perspective or othrographic projection type and modified the projection matrix accordingly

2022-05-19 01:45 UTC, Yuki-cpp requested changes
Prefer enum classes to straight up enums.
Additionally, setting up explicit values to enum fields isn't useful if those values don't have a specific meaning.

2022-05-19 01:45 UTC, Yuki-cpp commented on gl_depth_sim/include/gl_depth_sim/camera_properties.h
> +  enum ProjectionType { Perspective = 0, Orthographic = 1 };
```suggestion
  enum class ProjectionType { Perspective, Orthographic };
```

2022-05-19 01:45 UTC, Yuki-cpp commented on gl_depth_sim/include/gl_depth_sim/camera_properties.h
> +  ProjectionType projection = Perspective;
```suggestion
  ProjectionType projection = ProjectionType::Perspective;
```

2022-05-19 01:45 UTC, Yuki-cpp commented on gl_depth_sim/src/gl_depth_sim/sim_depth_camera.cpp
> +  if(camera.projection == gl_depth_sim::CameraProperties::Perspective)
```suggestion
  if(camera.projection == gl_depth_sim::CameraProperties::ProjectionType::Perspective)
```

2022-05-19 01:45 UTC, Yuki-cpp commented on gl_depth_sim/src/gl_depth_sim/sim_depth_camera.cpp
> +      if(camera_.projection == gl_depth_sim::CameraProperties::Perspective)
```suggestion
      if(camera_.projection == gl_depth_sim::CameraProperties::ProjectionType::Perspective)
```

2022-05-19 02:44 UTC, thomascent commented
@Yuki-cpp , makes sense, thanks for the review!

2022-05-19 03:07 UTC, Yuki-cpp approved these changes

2022-05-19 03:08 UTC, danielcranston requested changes
Nice feature!

Can we extend the test (https://github.com/ascentai/gl_depth_sim/blob/master/gl_depth_sim/test/utest.cpp) in some way to cover this? I have no idea if those values are correct.

Also, it seems CI is not run on PRs?

2023-01-06 01:48 UTC, danielcranston approved these changes

2023-01-06 01:49 UTC, merged